<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <CoverletOutputFormat>opencover</CoverletOutputFormat>
    <CollectCoverage>true</CollectCoverage>
    <CoverletOutput>$(MSBuildProjectDirectory)\coverage\</CoverletOutput>
    <RunSettingsFilePath>$(MSBuildProjectDirectory)\coverage.runsettings</RunSettingsFilePath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
    <PackageReference Include="NUnit" Version="4.5.1" />
    <PackageReference Include="NUnit.Analyzers" Version="4.12.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NUnit3TestAdapter" Version="6.1.0" />
    <PackageReference Include="ReportGenerator" Version="5.4.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Wallet.Api.Net\Wallet.Api.Net.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

  <ItemGroup>
    <None Update="TestData\**\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="PrepareCoverageReport" BeforeTargets="Test;VSTest">
    <ItemGroup>
      <OldCoverageReports Include="$(MSBuildProjectDirectory)\TestResults\**\coverage.cobertura.xml" />
    </ItemGroup>
    <Delete Files="@(OldCoverageReports)" ContinueOnError="true" />
    <RemoveDir Directories="$(MSBuildProjectDirectory)\coverage_report" ContinueOnError="true" />
  </Target>

  <Target Name="GenerateCoverageReport" AfterTargets="Test;VSTest">
    <ItemGroup>
      <CoverageReports Include="$(MSBuildProjectDirectory)\TestResults\**\coverage.cobertura.xml" />
    </ItemGroup>
    <ReportGenerator ReportFiles="@(CoverageReports)" TargetDirectory="$(MSBuildProjectDirectory)\coverage_report" ReportTypes="Html" Condition="'@(CoverageReports)' != ''" />
  </Target>

</Project>
